export const hotels = [
  {
    id: 1,
    img: "https://media1.orlandoweekly.com/orlando/imager/20-orlando-hotels-and-resorts-offering-pool-day-passes-for-locals/u/zoom/32039245/sheraton_orlando.png?cb=1657981797",
    name: "Four Season",
    place: "Berlin",
    price: "300$",
    rate: "4.6 Excellent",
  },
  {
    id: 2,
    img: "https://media2.orlandoweekly.com/orlando/imager/20-orlando-hotels-and-resorts-offering-pool-day-passes-for-locals/u/zoom/32039230/alof.png?cb=1657981795",
    name: "Five Season",
    place: "Roma",
    price: "200$",
    rate: "4.5 Excellent",
  },
  {
    id: 3,
    img: "https://media1.orlandoweekly.com/orlando/imager/20-orlando-hotels-and-resorts-offering-pool-day-passes-for-locals/u/zoom/32039231/balmoral_resort.jpg?cb=1657981795",
    name: "Four Season",
    place: "Cairo",
    price: "100$",
    rate: "4.2 Excellent",
  },
  {
    id: 4,
    img: "https://media2.orlandoweekly.com/orlando/imager/20-orlando-hotels-and-resorts-offering-pool-day-passes-for-locals/u/zoom/32039233/coco_key.jpg?cb=1657981795",
    name: "Three Season",
    place: "Turkey",
    price: "150$",
    rate: "4.6 Excellent",
  },
  {
    id: 5,
    img: "https://media2.orlandoweekly.com/orlando/imager/20-orlando-hotels-and-resorts-offering-pool-day-passes-for-locals/u/zoom/32039235/element.png?cb=1657981795",
    name: "Six Season",
    place: "America",
    price: "500$",
    rate: "9.6 Excellent",
  },
  {
    id: 6,
    img: "https://media2.orlandoweekly.com/orlando/imager/20-orlando-hotels-and-resorts-offering-pool-day-passes-for-locals/u/zoom/32039241/hyatt_regency.png?cb=1657981796",
    name: "Five Season",
    place: "Australia",
    price: "300$",
    rate: "4.6 Excellent",
  },
  {
    id: 7,
    img: "https://media2.orlandoweekly.com/orlando/imager/20-orlando-hotels-and-resorts-offering-pool-day-passes-for-locals/u/zoom/32039241/hyatt_regency.png?cb=1657981796",
    name: "Eight Season",
    place: "Italy",
    price: "230$",
    rate: "4.4 Excellent",
  },
  {
    id: 8,
    img: "https://media2.orlandoweekly.com/orlando/imager/20-orlando-hotels-and-resorts-offering-pool-day-passes-for-locals/u/zoom/32039241/hyatt_regency.png?cb=1657981796",
    name: "Seven Season",
    place: "China",
    price: "350$",
    rate: "4.6 Excellent",
  },
];
